package View;

/* autogenerated by Processing revision 1293 on 2023-08-28 */
import processing.core.*;

public class sketch extends PApplet {

/**
 * Bezier. 
 * 
 * The first two parameters for the bezier() function specify the 
 * first point in the curve and the last two parameters specify 
 * the last point. The middle parameters set the control points
 * that define the shape of the curve. 
 */

public void setup() {
  /* size commented out by preprocessor */; 
  stroke(255);
  noFill();
}

public void draw() {
  background(0);
  for (int i = 0; i < 200; i += 20) {
    bezier(mouseX-(i/2.0f), 40+i, 410, 20, 440, 300, 240-(i/16.0f), 300+(i/8.0f));
  }
}


  public void settings() { size(640, 360); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "View.sketch" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}